<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_dashboard_model');
        $this->load->model('M_dokter_model');
        $this->load->model('M_perawat_model');
        $this->load->model('M_pasien_model');
        $this->load->model('M_pelayanan_model');
		$this->load->model('M_metode_pembayaran_model');
        $this->load->model('M_jadwal_praktek_model');
        $this->load->model('M_jadwal_praktek_antrian_model');


    } 

    /*
     * Listing of company
     */
    function index()
    {

        if($this->session->userdata('islogin')) {

            if($this->session->userdata('level')=='admin') {

                $data['jumlah_dokter'] = $this->M_dokter_model->get_jumlah_all_m_dokter()->num_rows();
                $data['jumlah_perawat'] = $this->M_perawat_model->get_jumlah_all_m_perawat()->num_rows();
                $data['jumlah_pasien'] = $this->M_pasien_model->get_jumlah_all_m_pasien()->num_rows();
				$data['jumlah_metode_pembayaran'] = $this->M_metode_pembayaran_model->get_jumlah_all_m_metode_pembayaran()->num_rows();
                $data['jumlah_pelayanan'] = $this->M_pelayanan_model->get_jumlah_all_m_pelayanan()->num_rows();
                $data['jumlah_jadwal_praktek'] = $this->M_jadwal_praktek_model->get_jumlah_all_m_jadwal_praktek()->num_rows();
                $data['jumlah_antrian'] = $this->M_jadwal_praktek_antrian_model->get_jumlah_all_m_jadwal_praktek_antrian()->num_rows();   

            } elseif ($this->session->userdata('level')=='perawat') {

                 $data['jumlah_jadwal_praktek'] = $this->M_jadwal_praktek_model->get_jumlah_all_m_jadwal_praktek_aktif()->num_rows();
            }

            $data['_view'] = 'layouts/home';
            $this->load->view('layouts/main',$data);

        } else {

            $this->load->view('layouts/login');

        }

    }

    /*
     * Adding a new company
     */
    function login_proccess()
    {   
        $this->load->library('form_validation');

		$username = $this->input->post('username');
		$password = $this->input->post('password');
      

        $cek_login = $this->M_dashboard_model->cek_login($username,$password);

        if($cek_login->num_rows()>0) {

            $this->session->set_userdata('username',$username); // set session username

            $this->session->set_userdata('level',$cek_login->row()->status_login); // Status Kontak

            $this->session->set_userdata('nama',$cek_login->row()->nama); // Status Kontak

            $this->session->set_userdata('id',$cek_login->row()->pk); // Status Kontak
            
            $this->session->set_userdata('islogin', true); 
            
            redirect(site_url('dashboard'));
                       
        } else {
            //login gagal
            $this->session->set_flashdata('message','Username atau password salah');
            redirect('dashboard');
        }

    }  

    
    public function logout(){
        $this->session->sess_destroy();
        redirect('dashboard');
    }
    
}
