<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class gallery extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_gallery_model');

        if(!$this->session->userdata('islogin')) {

            redirect('dashboard');

        }
    } 

    /*
     * Listing of m_gallery
     */
    function index()
    {
        $data['m_gallery'] = $this->M_gallery_model->get_all_m_gallery();

        $data['_view'] = 'gallery/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new m_gallery
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('deskripsi','deskripsi gambar','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'deskripsi' => $this->input->post('deskripsi')
            );
            
            $M_gallery_id = $this->M_gallery_model->add_m_gallery($params);

            if(isset($_FILES['gambar']) && !empty($_FILES['gambar']['name'])){

                $config['upload_path']   = './resources/img/';
                $config['allowed_types'] = 'gif|jpg|png';
                $config['max_size']      = '0';
                $config['max_width']     = '0'; //ukuran lebar maksimal
                $config['max_height']    = '0'; //ukuran tinggi maksimal
                /*$config['file_name']     = $file_name;*/
                $config['remove_spaces'] = 'TRUE'; //menghapus spasi pada judul file
                $this->load->library('upload', $config);
                $this->upload->initialize($config);

                if($this->upload->do_upload('gambar')){
                    $aaa = array('upload_data' => $this->upload->data());
                    
                    $foto ['gambar']= $aaa['upload_data']['raw_name'].$aaa['upload_data']['file_ext'];
                   
                    $this->M_gallery_model->update_m_gallery($M_gallery_id,$foto);

                    //echo ("<SCRIPT LANGUAGE='JavaScript'>
                    //  window.alert('Upload Image Success')';
                    //  </SCRIPT>");

                } 

            }

            redirect('Gallery/index');
        }
        else
        {            
            $data['_view'] = 'gallery/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a m_gallery
     */
    function edit($pk)
    {   
        // check if the m_gallery exists before trying to edit it
        $data['m_gallery'] = $this->M_gallery_model->get_m_gallery($pk);
        
        if(isset($data['m_gallery']['pk']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('deskripsi','deskripsi gambar','required');

			if($this->form_validation->run())     
            {   
                $params = array(
					'deskripsi' => $this->input->post('deskripsi'),
                );

                $this->M_gallery_model->update_m_gallery($pk,$params);

                if(isset($_FILES['gambar']) && !empty($_FILES['gambar']['name'])){

                    $config['upload_path']   = './resources/img/';
                    $config['allowed_types'] = 'gif|jpg|png';
                    $config['max_size']      = '0';
                    $config['max_width']     = '0'; //ukuran lebar maksimal
                    $config['max_height']    = '0'; //ukuran tinggi maksimal
                    /*$config['file_name']     = $file_name;*/
                    $config['remove_spaces'] = 'TRUE'; //menghapus spasi pada judul file
                    $this->load->library('upload', $config);
                    $this->upload->initialize($config);

                    if($this->upload->do_upload('gambar')){
                        $aaa = array('upload_data' => $this->upload->data());
                        
                        $foto ['gambar'] = $aaa['upload_data']['raw_name'].$aaa['upload_data']['file_ext'];
                       
                        $this->M_gallery_model->update_m_gallery($pk,$foto);

                        //echo ("<SCRIPT LANGUAGE='JavaScript'>
                         // window.alert('Foto Wali berhasil diganti')';
                          //</SCRIPT>");

                    } 

                }

                redirect('gallery/index');
            }
            else
            {
                $data['_view'] = 'gallery/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The m_gallery you are trying to edit does not exist.');
    } 

    /*
     * Deleting m_gallery
     */
    function remove($pk)
    {   
        $m_gallery = $this->M_gallery_model->get_m_gallery($pk);

        // check if the m_gallery exists before trying to delete it
        if(isset($m_gallery['pk']))
        {
            $this->M_gallery_model->delete_m_gallery($pk);
            redirect('gallery/index');
        }
        else
            show_error('The m_gallery you are trying to delete does not exist.');
    }
    
}
