<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Jadwal_praktek extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_jadwal_praktek_model');

        
        if(!$this->session->userdata('islogin')) {

            redirect('dashboard');

        }
    } 

    /*
     * Listing of m_jadwal_praktek
     */
    function index()
    {   
        $data['m_jadwal_praktek'] = $this->M_jadwal_praktek_model->get_all_m_jadwal_praktek();

        if($this->session->userdata('level')=='admin') { 

            $data['_view'] = 'jadwal_praktek/index';
            $this->load->view('layouts/main',$data);

        } else if($this->session->userdata('level')=='perawat')  {

            $data['_view'] = 'jadwal_praktek/index_perawat';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Adding a new m_jadwal_praktek
     */
    function add()
    {   
        $this->load->library('form_validation');

		
		$this->form_validation->set_rules('dokter_fk','Dokter Fk','required');
		$this->form_validation->set_rules('pelayanan_fk','Pelayanan Fk','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'pembuat_fk' => $this->session->userdata('id'),
				'dokter_fk' => $this->input->post('dokter_fk'),
				'pelayanan_fk' => $this->input->post('pelayanan_fk'),
				'id_session_jadwal' => $this->input->post('id_session_jadwal'),
				'tanggal_praktek' => $this->input->post('tanggal_praktek'),
				'jam_praktek' => $this->input->post('jam_praktek'),
				//'total_pasien' => $this->input->post('total_pasien'),
				'batasan_pasien' => $this->input->post('batasan_pasien'),
				'status_terlaksana' => "Belum Terlaksana",
				'informasi_tambahan' => $this->input->post('informasi_tambahan'),
                'rentang_waktu' => $this->input->post('rentang_waktu'),
            );
            
            $m_jadwal_praktek_id = $this->M_jadwal_praktek_model->add_m_jadwal_praktek($params);
            redirect('jadwal_praktek/index');
        }
        else
        {

			$this->load->model('M_dokter_model');
            $this->load->model('M_kontak_model');

            $jumlah = $this->M_jadwal_praktek_model->get_jumlah_all_m_jadwal_praktek()->num_rows();
            
            if ($jumlah >= 999) {

                $no = 1;

            } else {

                $no = $jumlah+1;
            }

            if ($no < 10) {
                $nomor = '-00'.$no;
            } else if ($no < 100) {
                $nomor = '-0'.$no;
            } else {
                $nomor = '-'.$no;
            }

            $date = new DateTime();
            $tanggal = $date->format('dmY');

            $data['id_session_jadwal'] = $tanggal.$nomor;

			$data['all_m_dokter'] = $this->M_dokter_model->get_all_m_dokter();
			/*$data['all_m_kontak'] = $this->M_kontak_model->get_all_m_kontak();*/

			$this->load->model('M_pelayanan_model');
			$data['all_m_pelayanan'] = $this->M_pelayanan_model->get_all_m_pelayanan();
            
            $data['_view'] = 'jadwal_praktek/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a m_jadwal_praktek
     */
    function edit($pk)
    {   
        // check if the m_jadwal_praktek exists before trying to edit it
        $data['m_jadwal_praktek'] = $this->M_jadwal_praktek_model->get_m_jadwal_praktek($pk);
        
        if(isset($data['m_jadwal_praktek']['pk']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('dokter_fk','Dokter Fk','required');
			$this->form_validation->set_rules('pelayanan_fk','Pelayanan Fk','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'pembuat_fk' => $this->session->userdata('id'),
					'dokter_fk' => $this->input->post('dokter_fk'),
					'pelayanan_fk' => $this->input->post('pelayanan_fk'),
					'id_session_jadwal' => $this->input->post('id_session_jadwal'),
					'tanggal_praktek' => $this->input->post('tanggal_praktek'),
					'jam_praktek' => $this->input->post('jam_praktek'),
					'total_pasien' => $this->input->post('total_pasien'),
					'batasan_pasien' => $this->input->post('batasan_pasien'),
					'status_terlaksana' => $this->input->post('status_terlaksana'),
					'informasi_tambahan' => $this->input->post('informasi_tambahan'),
                    'rentang_waktu' => $this->input->post('rentang_waktu'),
                );

                $this->M_jadwal_praktek_model->update_m_jadwal_praktek($pk,$params);            
                redirect('jadwal_praktek/index');
            }
            else
            {
    			$this->load->model('M_dokter_model');
                $data['all_m_dokter'] = $this->M_dokter_model->get_all_m_dokter();
                /*$data['all_m_kontak'] = $this->M_kontak_model->get_all_m_kontak();*/

                $this->load->model('M_pelayanan_model');
                $data['all_m_pelayanan'] = $this->M_pelayanan_model->get_all_m_pelayanan();

                $data['_view'] = 'jadwal_praktek/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The m_jadwal_praktek you are trying to edit does not exist.');
    } 

    /*
     * Deleting m_jadwal_praktek
     */
    function remove($pk)
    {
        $this->M_cek_hapus->cek('m_jadwal_praktek_antrian','jadwal_praktek_fk',$pk,'Jadwal_praktek');

        $m_jadwal_praktek = $this->M_jadwal_praktek_model->get_m_jadwal_praktek($pk);

        // check if the m_jadwal_praktek exists before trying to delete it
        if(isset($m_jadwal_praktek['pk']))
        {
            $this->M_jadwal_praktek_model->delete_m_jadwal_praktek($pk);
            redirect('jadwal_praktek/index');
        }
        else
            show_error('The m_jadwal_praktek you are trying to delete does not exist.');
    }

    function start($pk)
    {

        $this->M_jadwal_praktek_model->start_m_jadwal_praktek($pk);

        redirect('jadwal_praktek/index');
    }

    function done($pk)
    {

        $this->M_jadwal_praktek_model->done_m_jadwal_praktek($pk);

        redirect('jadwal_praktek/index');
    }

    function open($pk)
    {

        $this->M_jadwal_praktek_model->open_m_jadwal_praktek($pk);

        redirect('jadwal_praktek/index');
    }
    
}
