<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Kontak extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_kontak_model');

        
        if(!$this->session->userdata('islogin')) {

            redirect('dashboard');

        }
    } 

    /*
     * Listing of m_kontak
     */
    function index()
    {
        $data['m_kontak'] = $this->M_kontak_model->get_all_m_kontak();

        $data['_view'] = 'kontak/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new m_kontak
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nomor_telepon','Nomor Telepon','required');
		$this->form_validation->set_rules('nama','Nama','required');
		$this->form_validation->set_rules('email','Email','required');
		$this->form_validation->set_rules('password','Password','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'password' => $this->input->post('password'),
				'nomor_registrasi' => $this->input->post('nomor_registrasi'),
				'tanggal_registrasi' => $this->input->post('tanggal_registrasi'),
				'nomor_telepon' => $this->input->post('nomor_telepon'),
				'nama' => $this->input->post('nama'),
				'jenis_kelamin' => $this->input->post('jenis_kelamin'),				
				'nama_ibu_kandung' => $this->input->post('nama_ibu_kandung'),
				'alamat' => $this->input->post('alamat'),
				'kecamatan' => $this->input->post('kecamatan'),
				'kelurahan' => $this->input->post('kelurahan'),
				'kota' => $this->input->post('kota'),
				'provinsi' => $this->input->post('provinsi'),
				'golongan_darah' => $this->input->post('golongan_darah'),
				'usia' => $this->input->post('usia'),
				'metode_pembayaran_fk' => $this->input->post('metode_pembayaran_fk'),
				'username' => $this->input->post('username'),
				'email' => $this->input->post('email'),
				'status_login' => $this->input->post('status_login'),
            );
            
            $m_kontak_id = $this->M_kontak_model->add_m_kontak($params);
            redirect('kontak/index');
        }
        else
        {            
            $data['_view'] = 'kontak/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a m_kontak
     */
    function edit($pk)
    {   
        // check if the m_kontak exists before trying to edit it
        $data['m_kontak'] = $this->M_kontak_model->get_m_kontak($pk);
        
        if(isset($data['m_kontak']['pk']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nomor_telepon','Nomor Telepon','required');
			$this->form_validation->set_rules('nama','Nama','required');
			$this->form_validation->set_rules('email','Email','required');
			$this->form_validation->set_rules('password','Password','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'password' => $this->input->post('password'),
					'nomor_registrasi' => $this->input->post('nomor_registrasi'),
					'tanggal_registrasi' => $this->input->post('tanggal_registrasi'),
					'nomor_telepon' => $this->input->post('nomor_telepon'),
					'nama' => $this->input->post('nama'),
					'jenis_kelamin' => $this->input->post('jenis_kelamin'),				
					'nama_ibu_kandung' => $this->input->post('nama_ibu_kandung'),
					'alamat' => $this->input->post('alamat'),
					'kecamatan' => $this->input->post('kecamatan'),
					'kelurahan' => $this->input->post('kelurahan'),
					'kota' => $this->input->post('kota'),
					'provinsi' => $this->input->post('provinsi'),
					'golongan_darah' => $this->input->post('golongan_darah'),
					'usia' => $this->input->post('usia'),
					'metode_pembayaran_fk' => $this->input->post('metode_pembayaran_fk'),
					'username' => $this->input->post('username'),
					'email' => $this->input->post('email'),
					'status_login' => $this->input->post('status_login'),
                );

                $this->M_kontak_model->update_m_kontak($pk,$params);            
                redirect('kontak/index');
            }
            else
            {
                $data['_view'] = 'kontak/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The m_kontak you are trying to edit does not exist.');
    } 

    /*
     * Deleting m_kontak
     */
    function remove($pk)
    {
        $m_kontak = $this->M_kontak_model->get_m_kontak($pk);

        // check if the m_kontak exists before trying to delete it
        if(isset($m_kontak['pk']))
        {
            $this->M_kontak_model->delete_m_kontak($pk);
            redirect('kontak/index');
        }
        else
            show_error('The m_kontak you are trying to delete does not exist.');
    }
    
}
