<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Metode_pembayaran extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_metode_pembayaran_model');

        if(!$this->session->userdata('islogin')) {

            redirect('dashboard');

        }
    } 

    /*
     * Listing of m_metode_pembayaran
     */
    function index()
    {
        $data['m_metode_pembayaran'] = $this->M_metode_pembayaran_model->get_all_m_metode_pembayaran();

        $data['_view'] = 'metode_pembayaran/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new m_metode_pembayaran
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('metode_bayar','Metode Bayar','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'metode_bayar' => $this->input->post('metode_bayar')
            );
            
            $M_metode_pembayaran_id = $this->M_metode_pembayaran_model->add_m_metode_pembayaran($params);
            redirect('metode_pembayaran/index');
        }
        else
        {            
            $data['_view'] = 'metode_pembayaran/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a m_metode_pembayaran
     */
    function edit($pk)
    {   
        // check if the m_metode_pembayaran exists before trying to edit it
        $data['m_metode_pembayaran'] = $this->M_metode_pembayaran_model->get_m_metode_pembayaran($pk);
        
        if(isset($data['m_metode_pembayaran']['pk']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('metode_bayar','Metode Bayar','required');

			if($this->form_validation->run())     
            {   
                $params = array(
					'metode_bayar' => $this->input->post('metode_bayar'),
                );

                $this->M_metode_pembayaran_model->update_m_metode_pembayaran($pk,$params);
                
                redirect('metode_pembayaran/index');
            }
            else
            {
                $data['_view'] = 'metode_pembayaran/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The m_metode_pembayaran you are trying to edit does not exist.');
    } 

    /*
     * Deleting m_metode_pembayaran
     */
    function remove($pk)
    {   
        $m_metode_pembayaran = $this->M_metode_pembayaran_model->get_m_metode_pembayaran($pk);

        // check if the m_metode_pembayaran exists before trying to delete it
        if(isset($m_metode_pembayaran['pk']))
        {
            $this->M_metode_pembayaran_model->delete_m_metode_pembayaran($pk);
            redirect('metode_pembayaran/index');
        }
        else
            show_error('The m_metode_pembayaran you are trying to delete does not exist.');
    }
    
}
