<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Pasien extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_pasien_model');

        
        if(!$this->session->userdata('islogin')) {

            redirect('dashboard');

        }
    } 

    /*
     * Listing of m_pasien
     */
    function index()
    {
        $data['m_pasien'] = $this->M_pasien_model->get_all_m_pasien();

        $data['_view'] = 'pasien/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new m_pasien
     */
    function add()
    {   
        $this->load->library('form_validation');		

		$this->form_validation->set_rules('nomor_telepon','Nomor Telepon','required');
		$this->form_validation->set_rules('nama','Nama','required');				$this->form_validation->set_rules('nama_ibu_kandung','Nama Ibu Kandung','required');						$this->form_validation->set_rules('jenis_kelamin','Jenis Kelamin','required');
		$this->form_validation->set_rules('email','Email','required');
		$this->form_validation->set_rules('password','Password','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'password' => $this->input->post('password'),
				'nomor_registrasi' => $this->input->post('nomor_registrasi'),
				'tanggal_registrasi' => $this->input->post('tanggal_registrasi'),
				'nomor_telepon' => $this->input->post('nomor_telepon'),
				'nama' => $this->input->post('nama'),								'jenis_kelamin' => $this->input->post('jenis_kelamin'),								'nama_ibu_kandung' => $this->input->post('nama_ibu_kandung'),
				'alamat' => $this->input->post('alamat'),
				'kecamatan' => $this->input->post('kecamatan'),
				'kelurahan' => $this->input->post('kelurahan'),
				'kota' => $this->input->post('kota'),
				'provinsi' => $this->input->post('provinsi'),
				'golongan_darah' => $this->input->post('golongan_darah'),
				'usia' => $this->input->post('usia'),										'username' => $this->input->post('username'),
				'email' => $this->input->post('email'),
				'status_login' => 'pasien',
                'approved' => '1',
            );
            
            $m_pasien_id = $this->M_pasien_model->add_m_pasien($params);
            redirect('pasien/index');
        }
        else
        {            			$this->load->model('M_pasien_model');            $this->load->model('M_kontak_model');            $jumlah = $this->M_pasien_model->get_jumlah_all_m_n_pasien()->row_array();                        $lastID = $jumlah['nomor_registrasi'];            $lastNoUrut = substr($lastID, 4, 9);            $nextNoUrut = $lastNoUrut + 1;            $data['nomor_registrasi'] = "PA".sprintf("%04s",$nextNoUrut);            $this->load->model('M_metode_pembayaran_model');            $data['all_m_metode_pembayaran'] = $this->M_metode_pembayaran_model->get_all_m_metode_pembayaran();                        $data['_view'] = 'pasien/add';            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a m_pasien
     */
    function edit($pk)
    {   
        // check if the m_pasien exists before trying to edit it
        $data['m_pasien'] = $this->M_pasien_model->get_m_pasien($pk);
        
        if(isset($data['m_pasien']['pk']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nomor_telepon','Nomor Telepon','required');
			$this->form_validation->set_rules('nama','Nama','required');						$this->form_validation->set_rules('nama_ibu_kandung','Nama Ibu Kandung','required');											$this->form_validation->set_rules('jenis_kelamin','Jenis Kelamin','required');
			$this->form_validation->set_rules('email','Email','required');
			$this->form_validation->set_rules('password','Password','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'password' => $this->input->post('password'),
					'nomor_registrasi' => $this->input->post('nomor_registrasi'),
					'tanggal_registrasi' => $this->input->post('tanggal_registrasi'),
					'nomor_telepon' => $this->input->post('nomor_telepon'),
					'nama' => $this->input->post('nama'),										'jenis_kelamin' => $this->input->post('jenis_kelamin'),									'nama_ibu_kandung' => $this->input->post('nama_ibu_kandung'),
					'alamat' => $this->input->post('alamat'),
					'kecamatan' => $this->input->post('kecamatan'),
					'kelurahan' => $this->input->post('kelurahan'),
					'kota' => $this->input->post('kota'),
					'provinsi' => $this->input->post('provinsi'),
					'golongan_darah' => $this->input->post('golongan_darah'),
					'usia' => $this->input->post('usia'),														'username' => $this->input->post('username'),
					'email' => $this->input->post('email'),
					'status_login' => 'pasien',
                    'approved' => '1',
                );

                $this->M_pasien_model->update_m_pasien($pk,$params);            
                redirect('pasien/index');
            }
            else
            {								
                $data['_view'] = 'pasien/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The m_pasien you are trying to edit does not exist.');
    } 

    /*
     * Deleting m_pasien
     */
    function remove($pk)
    {
        $this->M_cek_hapus->cek('m_jadwal_praktek_antrian','pasien_fk',$pk,'pasien');

        $m_pasien = $this->M_pasien_model->get_m_pasien($pk);

        // check if the m_pasien exists before trying to delete it
        if(isset($m_pasien['pk']))
        {
            $this->M_pasien_model->delete_m_pasien($pk);
            redirect('pasien/index');
        }
        else
            show_error('The m_pasien you are trying to delete does not exist.');
    }

    public function cek_nomor_registrasi(){
        $nomor_registrasi = $this->input->post('nomor_registrasi');
        $query = $this->M_pasien_model->cek_nomor_registrasi($nomor_registrasi);
        $status           = "true";
        if($query){ $status = "false"; }
            echo $status;
    }

    public function cek_nomor_registrasi_edit($pk){
        $nomor_registrasi = $this->input->post('nomor_registrasi_edit');
        $query = $this->M_pasien_model->cek_nomor_registrasi_edit($nomor_registrasi,$pk);
        $status           = "true";
        if($query){ $status = "false"; }
            echo $status;
    }

     public function cek_username(){
        $username = $this->input->post('username');
        $query = $this->M_pasien_model->cek_username($username);
        $status           = "true";
        if($query){ $status = "false"; }
            echo $status;
    }

    public function cek_username_edit($pk){
        $username = $this->input->post('username_edit');
        $query = $this->M_pasien_model->cek_username_edit($username,$pk);
        $status           = "true";
        if($query){ $status = "false"; }
            echo $status;
    }

    function approve(){
        $pk = $this->input->post('pk');
        $params['nomor_registrasi'] = $this->input->post('nomor_registrasi');
        $params['approved'] = '1';

        $this->M_pasien_model->update_m_pasien($pk,$params);            
        redirect('pasien/index');

    }
    
}
