<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Pelayanan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_pelayanan_model');

        
        if(!$this->session->userdata('islogin')) {

            redirect('dashboard');

        }
    } 

    /*
     * Listing of m_pelayanan
     */
    function index()
    {
        $data['m_pelayanan'] = $this->M_pelayanan_model->get_all_m_pelayanan();

        $data['_view'] = 'pelayanan/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new m_pelayanan
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('id_pelayanan','Id Pelayanan','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nama_pelayanan' => $this->input->post('nama_pelayanan'),
				'id_pelayanan' => $this->input->post('id_pelayanan'),
				'image_pelayanan_head' => $this->input->post('image_pelayanan_head'),
				'image_pelayanan_foot' => $this->input->post('image_pelayanan_foot'),
				'deskripsi_pelayanan' => $this->input->post('deskripsi_pelayanan'),
                'jenis_pelayanan_fk' => $this->input->post('jenis_pelayanan_fk'),
            );
            
            $m_pelayanan_id = $this->M_pelayanan_model->add_m_pelayanan($params);

            if(isset($_FILES['gambar']) && !empty($_FILES['gambar']['name'])){

                $config['upload_path']   = './resources/img/';
                $config['allowed_types'] = 'gif|jpg|png';
                $config['max_size']      = '0';
                $config['max_width']     = '0'; //ukuran lebar maksimal
                $config['max_height']    = '0'; //ukuran tinggi maksimal
                /*$config['file_name']     = $file_name;*/
                $config['remove_spaces'] = 'TRUE'; //menghapus spasi pada judul file
                $this->load->library('upload', $config);
                $this->upload->initialize($config);

                if($this->upload->do_upload('gambar')){
                    $aaa = array('upload_data' => $this->upload->data());
                    
                    $foto ['image']= $aaa['upload_data']['raw_name'].$aaa['upload_data']['file_ext'];
                   
                    $this->M_pelayanan_model->update_m_pelayanan($m_pelayanan_id,$foto);

                    //echo ("<SCRIPT LANGUAGE='JavaScript'>
                    //  window.alert('Upload Image Success')';
                     // </SCRIPT>");

                } 

            }

            redirect('pelayanan/index');
        }
        else
        {            
            $data['_view'] = 'pelayanan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a m_pelayanan
     */
    function edit($pk)
    {   
        // check if the m_pelayanan exists before trying to edit it
        $data['m_pelayanan'] = $this->M_pelayanan_model->get_m_pelayanan($pk);
        
        if(isset($data['m_pelayanan']['pk']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('id_pelayanan','Id Pelayanan','required');

            
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nama_pelayanan' => $this->input->post('nama_pelayanan'),
					'id_pelayanan' => $this->input->post('id_pelayanan'),
					'image_pelayanan_head' => $this->input->post('image_pelayanan_head'),
					'image_pelayanan_foot' => $this->input->post('image_pelayanan_foot'),
					'deskripsi_pelayanan' => $this->input->post('deskripsi_pelayanan'),
                    'jenis_pelayanan_fk' => $this->input->post('jenis_pelayanan_fk'),
                );

                $this->M_pelayanan_model->update_m_pelayanan($pk,$params);

                /*echo $_FILES['gambar']['name'];exit;*/

                if(isset($_FILES['gambar']) && !empty($_FILES['gambar']['name'])){

                    $config['upload_path']   = './resources/img/';
                    $config['allowed_types'] = 'gif|jpg|png';
                    $config['max_size']      = '0';
                    $config['max_width']     = '0'; //ukuran lebar maksimal
                    $config['max_height']    = '0'; //ukuran tinggi maksimal
                    /*$config['file_name']     = $file_name;*/
                    $config['remove_spaces'] = 'TRUE'; //menghapus spasi pada judul file
                    $this->load->library('upload', $config);
                    $this->upload->initialize($config);

                    if($this->upload->do_upload('gambar')){
                        $aaa = array('upload_data' => $this->upload->data());
                        
                        $foto ['image']= $aaa['upload_data']['raw_name'].$aaa['upload_data']['file_ext'];
                       
                        $this->M_pelayanan_model->update_m_pelayanan($pk,$foto);

                        //echo ("<SCRIPT LANGUAGE='JavaScript'>
                         // window.alert('Foto Wali berhasil diganti')';
                          //</SCRIPT>");

                    } 

                }

                redirect('pelayanan/index');
            }
            else
            {
                $data['_view'] = 'pelayanan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The m_pelayanan you are trying to edit does not exist.');
    } 

    /*
     * Deleting m_pelayanan
     */
    function remove($pk)
    {   
        $this->M_cek_hapus->cek('m_jadwal_praktek','pelayanan_fk',$pk,'pelayanan');

        $m_pelayanan = $this->M_pelayanan_model->get_m_pelayanan($pk);

        // check if the m_pelayanan exists before trying to delete it
        if(isset($m_pelayanan['pk']))
        {
            $this->M_pelayanan_model->delete_m_pelayanan($pk);
            redirect('pelayanan/index');
        }
        else
            show_error('The m_pelayanan you are trying to delete does not exist.');
    }
    
}
