<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class M_dashboard_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
        public function cek_login($username,$password){
        $this->db->select("*")
        ->from("m_kontak")
        ->where("username",$username)
        ->where("password",$password);
        /*->where("status_login",'admin');*/
        return $this->db->get();
    }
}
