<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class M_gallery_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get m_gallery by pk
     */
    function get_m_gallery($pk)
    {
        return $this->db->get_where('m_gallery',array('pk'=>$pk))->row_array();
    }
    
    /*
     * Get all m_gallery
     */
    function get_all_m_gallery()
    {   
        $this->db->select('*');
        $this->db->from('m_gallery');
        return $this->db->get()->result_array();
    }

    function get_jumlah_all_m_gallery()
    {
        return $this->db->get('m_gallery');
    }
    
    /*
     * function to add new m_gallery
     */
    function add_m_gallery($params)
    {
        $this->db->insert('m_gallery',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update m_gallery
     */
    function update_m_gallery($pk,$params)
    {
        $this->db->where('pk',$pk);
        $response = $this->db->update('m_gallery',$params);
        if($response)
        {
            return "m_gallery updated successfully";
        }
        else
        {
            return "Error occuring while updating m_gallery";
        }
    }
    
    /*
     * function to delete m_gallery
     */
    function delete_m_gallery($pk)
    {
        $response = $this->db->delete('m_gallery',array('pk'=>$pk));
        if($response)
        {
            return "m_gallery deleted successfully";
        }
        else
        {
            return "Error occuring while deleting m_gallery";
        }
    }
}
