<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class M_jadwal_praktek_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
        date_default_timezone_set("Asia/Jakarta");
    }
    
    /*
     * Get m_jadwal_praktek by pk
     */
    function get_m_jadwal_praktek($pk)
    {
        return $this->db->get_where('m_jadwal_praktek',array('pk'=>$pk))->row_array();
    }
    
    /*
     * Get all m_jadwal_praktek
     */
    function get_all_m_jadwal_praktek()
    {
        $where ='';
        if($this->session->userdata('level')=='perawat') { 

            $where = " AND a.status_terlaksana = 'Sedang Terlaksana' ";
        }

         return $this->db->query("SELECT a.pk as id,pembuat_fk,dokter_fk,b.nama as pembuat,c.nama as dokter,
                                  d.nama_pelayanan,informasi_tambahan,total_pasien,batasan_pasien,status_terlaksana,
                                  rentang_waktu,perawat_fk,pelayanan_fk,nama_pelayanan,
                                  id_session_jadwal,tanggal_praktek,jam_praktek,e.nama as perawat
                                  FROM m_jadwal_praktek a
                                  LEFT JOIN m_pelayanan d on a.pelayanan_fk = d.pk
                                  LEFT JOIN m_kontak b on a.pembuat_fk = b.pk
                                  LEFT JOIN m_kontak c on a.dokter_fk = c.pk
                                  LEFT JOIN m_kontak e on a.perawat_fk = e.pk
                                  WHERE 1=1 $where
                                  ORDER BY tanggal_praktek desc")->result_array();
    }
	
	function get_all_m_jadwal_praktek_belum_selesai()
    {
         return $this->db->query("SELECT a.pk as id,pembuat_fk,dokter_fk,b.nama as pembuat,c.nama as dokter,
                                  d.nama_pelayanan,informasi_tambahan,total_pasien,batasan_pasien,status_terlaksana,
                                  rentang_waktu,perawat_fk,pelayanan_fk,nama_pelayanan,
                                  id_session_jadwal,tanggal_praktek,jam_praktek,e.nama as perawat
                                  FROM m_jadwal_praktek a
                                  LEFT JOIN m_pelayanan d on a.pelayanan_fk = d.pk
                                  LEFT JOIN m_kontak b on a.pembuat_fk = b.pk
                                  LEFT JOIN m_kontak c on a.dokter_fk = c.pk
                                  LEFT JOIN m_kontak e on a.perawat_fk = e.pk
                                  WHERE a.status_terlaksana <> 'Sudah Terlaksana'
                                  ORDER BY tanggal_praktek desc")->result_array();
    }


    function get_jumlah_all_m_jadwal_praktek()
    {
         return $this->db->query('SELECT *,a.pk as id,b.nama as pembuat,c.nama as dokter,nama_pelayanan
                                  FROM m_jadwal_praktek a
                                  LEFT JOIN m_kontak b on a.pembuat_fk = b.pk
                                  LEFT JOIN m_kontak c on a.dokter_fk = c.pk
                                  LEFT JOIN m_pelayanan d on a.pelayanan_fk = d.pk');
    }

    function get_jumlah_all_m_jadwal_praktek_aktif()
    {
         return $this->db->query("SELECT *,a.pk as id,b.nama as pembuat,c.nama as dokter,nama_pelayanan
                                  FROM m_jadwal_praktek a
                                  LEFT JOIN m_kontak b on a.pembuat_fk = b.pk
                                  LEFT JOIN m_kontak c on a.dokter_fk = c.pk
                                  LEFT JOIN m_pelayanan d on a.pelayanan_fk = d.pk
                                  WHERE a.status_terlaksana='Sedang Terlaksana'");
    }
    
    /*
     * function to add new m_jadwal_praktek
     */
    function add_m_jadwal_praktek($params)
    {
        $this->db->insert('m_jadwal_praktek',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update m_jadwal_praktek
     */
    function update_m_jadwal_praktek($pk,$params)
    {
        $this->db->where('pk',$pk);
        $response = $this->db->update('m_jadwal_praktek',$params);
        if($response)
        {
            return "m_jadwal_praktek updated successfully";
        }
        else
        {
            return "Error occuring while updating m_jadwal_praktek";
        }
    }
    
    /*
     * function to delete m_jadwal_praktek
     */
    function delete_m_jadwal_praktek($pk)
    {
        $response = $this->db->delete('m_jadwal_praktek',array('pk'=>$pk));
        if($response)
        {
            return "m_jadwal_praktek deleted successfully";
        }
        else
        {
            return "Error occuring while deleting m_jadwal_praktek";
        }
    }
    
    function start_m_jadwal_praktek($pk)
    {
        $params['status_terlaksana'] = 'Sedang Terlaksana';

        $this->db->where('pk',$pk);
        $this->db->update('m_jadwal_praktek',$params);

        $params_dua['status_antrian'] = 'Terjadwalkan';

        $this->db->where('jadwal_praktek_fk',$pk);
        $response = $this->db->update('m_jadwal_praktek_antrian',$params_dua);

        if($response)
        {
            return "m_jadwal_praktek updated successfully";
        }
        else
        {
            return "Error occuring while updating m_jadwal_praktek";
        }
    }

    function done_m_jadwal_praktek($pk)
    {

        if ($this->session->userdata('level')=='admin') {

            $cek_all = $this->db->query("select * from m_jadwal_praktek_antrian where jadwal_praktek_fk='$pk'")->num_rows();
                                         
            $cek_status = $this->db->query("select * from m_jadwal_praktek_antrian 
                                            where (jadwal_praktek_fk='$pk' and (status_antrian='Selesai' OR status_antrian='Batal'))")->num_rows();
                                            
            if($cek_status != $cek_all ){
                
                echo ("<SCRIPT LANGUAGE='JavaScript'>
                      window.alert('Gagal Mengakhiri Session , Antrian Pasien Belum Selesai');
                      window.location.href='".site_url('jadwal_praktek')."';
                      </SCRIPT>");
                      
                      exit;
                
            }
			else{
				$params['status_terlaksana'] = 'Sudah Terlaksana';                                   
				$this->db->where('pk',$pk);
				$response = $this->db->update('m_jadwal_praktek',$params);
			}

        } else {

            $params['status_terlaksana'] = 'Sudah Terlaksana';

            $this->db->query("update m_jadwal_praktek_antrian set status_antrian='Selesai'
                              where status_antrian='Tindakan' and jadwal_praktek_fk=".$pk);

            $this->db->query("update m_jadwal_praktek_antrian set status_antrian='Batal'
                              where status_antrian='Terjadwalkan' and jadwal_praktek_fk=".$pk);
                         
            $this->db->where('pk',$pk);
            $response = $this->db->update('m_jadwal_praktek',$params);

            if($response)
            {
                return "m_jadwal_praktek updated successfully";
            }
            else
            {
                return "Error occuring while updating m_jadwal_praktek";
            }

        }
    }

    function open_m_jadwal_praktek($pk)
    {
        $params['status_terlaksana'] = 'Belum Terlaksana';

        $this->db->where('pk',$pk);
        $response = $this->db->update('m_jadwal_praktek',$params);

        if($response)
        {
            return "m_jadwal_praktek updated successfully";
        }
        else
        {
            return "Error occuring while updating m_jadwal_praktek";
        }
    }
    
	function get_total_pasien($pk){
		$antrian = $this->db->query("select * from m_jadwal_praktek where pk = '".$pk."'")->row_array();
		return $antrian['total_pasien'];
	}
	
	function update_total_pasien($pk, $params){
		$this->db->where('pk',$pk);
        $response = $this->db->update('m_jadwal_praktek',$params);

        if($response)
        {
            return "m_jadwal_praktek updated successfully";
        }
        else
        {
            return "Error occuring while updating m_jadwal_praktek";
        }
	}
	
	function get_batasan_pasien($pk){
		$antrian = $this->db->query("select * from m_jadwal_praktek where pk = '".$pk."'")->row_array();
		return $antrian['batasan_pasien'];
	}
}
