<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class M_kontak_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get m_kontak by pk
     */
    function get_m_kontak($pk)
    {
        return $this->db->get_where('m_kontak',array('pk'=>$pk))->row_array();
    }
    
    /*
     * Get all m_kontak
     */
    function get_all_m_kontak()
    {
        return $this->db->get('m_kontak')->result();
    }
    
    /*
     * function to add new m_kontak
     */
    function add_m_kontak($params)
    {
        $this->db->insert('m_kontak',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update m_kontak
     */
    function update_m_kontak($pk,$params)
    {
        $this->db->where('pk',$pk);
        $response = $this->db->update('m_kontak',$params);
        if($response)
        {
            return "m_kontak updated successfully";
        }
        else
        {
            return "Error occuring while updating m_kontak";
        }
    }
    
    /*
     * function to delete m_kontak
     */
    function delete_m_kontak($pk)
    {
        $response = $this->db->delete('m_kontak',array('pk'=>$pk));
        if($response)
        {
            return "m_kontak deleted successfully";
        }
        else
        {
            return "Error occuring while deleting m_kontak";
        }
    }
}
