<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class M_metode_pembayaran_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get m_metode_pembayaran by pk
     */
    function get_m_metode_pembayaran($pk)
    {
        return $this->db->get_where('m_metode_pembayaran',array('pk'=>$pk))->row_array();
    }
    
    /*
     * Get all m_metode_pembayaran
     */
    function get_all_m_metode_pembayaran()
    {   
        $this->db->select('*');
        $this->db->from('m_metode_pembayaran');        
        return $this->db->get()->result_array();
    }

    function get_jumlah_all_m_metode_pembayaran()
    {
        return $this->db->get('m_metode_pembayaran');
    }
    
    /*
     * function to add new m_metode_pembayaran
     */
    function add_m_metode_pembayaran($params)
    {
        $this->db->insert('m_metode_pembayaran',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update m_metode_pembayaran
     */
    function update_m_metode_pembayaran($pk,$params)
    {
        $this->db->where('pk',$pk);
        $response = $this->db->update('m_metode_pembayaran',$params);
        if($response)
        {
            return "m_metode_pembayaran updated successfully";
        }
        else
        {
            return "Error occuring while updating m_metode_pembayaran";
        }
    }
    
    /*
     * function to delete m_metode_pembayaran
     */
    function delete_m_metode_pembayaran($pk)
    {
        $response = $this->db->delete('m_metode_pembayaran',array('pk'=>$pk));
        if($response)
        {
            return "m_metode_pembayaran deleted successfully";
        }
        else
        {
            return "Error occuring while deleting m_metode_pembayaran";
        }
    }
}
