<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class M_perawat_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get m_kontak by pk
     */
    function get_m_perawat($pk)
    {
        return $this->db->get_where('m_kontak',array('pk'=>$pk))->row_array();
    }
    
    
    /*
     * Get all m_kontak
     */
    function get_all_m_perawat()
    {
        return $this->db->get_where('m_kontak',array('status_login'=>'perawat'))->result();
    }

    function get_jumlah_all_m_perawat()
    {
        return $this->db->get_where('m_kontak',array('status_login'=>'perawat'));
    }
    
    /*
     * function to add new m_kontak
     */
    function add_m_perawat($params)
    {
        $this->db->insert('m_kontak',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update m_kontak
     */
    function update_m_perawat($pk,$params)
    {
        $this->db->where('pk',$pk);
        $response = $this->db->update('m_kontak',$params);
        if($response)
        {
            return "Pasien updated successfully";
        }
        else
        {
            return "Error occuring while updating m_kontak";
        }
    }
    
    /*
     * function to delete m_kontak
     */
    function delete_m_perawat($pk)
    {
        $response = $this->db->delete('m_kontak',array('pk'=>$pk));
        if($response)
        {
            return "Pasien deleted successfully";
        }
        else
        {
            return "Error occuring while deleting m_kontak";
        }
    }

    public function cek_nomor_registrasi($nomor_registrasi){
        $this->db->where("nomor_registrasi",$nomor_registrasi);
        $this->db->where("status_login",'perawat');
        return $this->db->get("m_kontak")->result();
    }

    public function cek_nomor_registrasi_edit($nomor_registrasi,$pk){
        $this->db->where("pk !=",$pk);
        $this->db->where("nomor_registrasi",$nomor_registrasi);
        $this->db->where("status_login",'perawat');
        return $this->db->get("m_kontak")->result();
    }

    public function cek_username($username){
        $this->db->where("username",$username);
        /*$this->db->where("status_login",'dokter');*/
        return $this->db->get("m_kontak")->result();
    }

    public function cek_username_edit($username,$pk){
        $this->db->where("pk !=",$pk);
        $this->db->where("username",$username);
        /*$this->db->where("status_login",'dokter');*/
        return $this->db->get("m_kontak")->result();
    }
}
